version: '3'

services:

  api:
    build: api
    restart: always
    ports:
      - 8080:8080

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  # frontend:
  #   build: frontend