version: '3'

services:

  api:
    build: api
    restart: always
    environment:
      APIACCESS_ENDPOINT: "http://apiaccesstracker:8080/accessevent"
    ports:
      - "${MYCHSA_API_PORT}:8080"
    depends_on:
      - apiaccesstracker

  db:
    build: db
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: "${MYCHSA_MYSQL_PASSWORD}"
    volumes:
      - ./db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/:ro

  frontend:
    build: 
      context: frontend
      args:
        API_URL: "${MYCHSA_API_URL}"
    restart: always
    ports:
      - "${MYCHSA_PORT}:80"
    depends_on:
      - api

  apiaccesstracker:
    build: apiaccesstracker
    restart: always
    environment:
      MYSQL_HOST: db
      MYSQL_DATABASE: api
      MYSQL_USER: api
      MYSQL_PASSWORD: "${MYCHSA_MYSQL_PASSWORD}"      
      MYSQL_PORT: 3306
    depends_on:
      - db
