version: '3'

services:

  api:
    build: api
    restart: always
    ports:
      - "${PORT:-8080}:8080"

  db:
    build: db
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: apiaccess
      MYSQL_USER: apiaccess
      MYSQL_PASSWORD: apiaccess

  frontend:
    build: frontend
    restart: always