name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Build docker images
        run: docker-compose build
        
      - name: Run e2e tests
        run: docker-compose up -d && source e2e/run_e2e.sh
